### ISSUE TITLE
Fail to send large files

### ISSUE THREAD

**Issue by EmmanuelME78** [bolner/AsyncFastCGI.NET#1]
In  FifoStream.cs, class FifoStream, line 129 your code is: 

``` csharp
current.offset -= remaining;
```
It should be
``` csharp
current.offset += remaining;
```

**Comment by bolner** [comment]
@EmmanuelME78 Hi, sorry for the late response. I just noticed your post. Checking.

**Comment by bolner** [comment]
@EmmanuelME78 Thanks for reporting. I've pushed the fix to NuGet too: https://www.nuget.org/packages/AsyncFastCGI.NET/1.0.1
