### ISSUE TITLE
Issue: last http header missing

### ISSUE THREAD

**Issue by jcm7612** [bolner/AsyncFastCGI.NET#2]
Hello, I found issue that parsing of last header isn’t working.
So I changed lib/FifoStream.cs line 184 line

current

`                
if (cursor + nameLength + valueLength >= length - 1) {
                    break;
}
`

proposal

`                
if (cursor + nameLength + valueLength > length) {
                    break;
}
`

If there’s any better solution, please let me know

**Comment by bolner** [comment]
Hi @jcm7612,

yes, what you wrote is correct:
![name-value](https://user-images.githubusercontent.com/2199459/137554856-24d10c30-4db6-41cd-ba53-e0f4abcb419c.png)

In this case `2 + 4 + 2 >= 8 - 1` would fail by not one but even two.

But `2 + 4 + 2 > 8` would return false correctly.

Fixing it.

**Comment by bolner** [comment]
Added the new version to NuGet too:
- https://www.nuget.org/packages/AsyncFastCGI.NET/1.0.2
